name: "BB CI: Flow"
run-name: "CI Flow :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/bb-ci-flow.yml"
      - ".github/workflows/bb-ci-module.yml"
      - "flow/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/bb-ci-flow.yml"
      - ".github/workflows/bb-ci-module.yml"
      - "flow/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  ci:
    uses: "./.github/workflows/bb-ci-module.yml"
    secrets: inherit
    with:
      exclude-unit-tests: true
      module: "flow"
