name: "CI: Bob"
run-name: "CI Bob :: ${{ github.event.head_commit.message || github.event.pull_request.title }}"

concurrency:
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.ref}}

on:
  workflow_dispatch:
  pull_request:
    paths:
      - ".github/workflows/ci-bob.yml"
      - ".github/workflows/ci-module.yml"
      - "bob/**"
      - "foundry.base.toml"
      - "package.json"
  push:
    branches:
      - "main"
      - "staging"
    paths:
      - ".github/workflows/ci-bob.yml"
      - ".github/workflows/ci-module.yml"
      - "bob/**"
      - "foundry.base.toml"
      - "package.json"

jobs:
  ci:
    uses: "./.github/workflows/ci-module.yml"
    secrets: inherit
    with:
      exclude-invariant-tests: true
      exclude-unit-tests: true
      match-path-coverage: "tests/*/integration/**/*.sol"
      match-path-integration: "tests/*/integration/**/*.sol"
      module: "bob"
